// Code generated by mcpgen. DO NOT EDIT.

package tools

import (
	"github.com/fzxbl/mcp-toolify/runtime"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

func RegisterAll(s *mcp.Server, opts runtime.RegisterOptions) {
	Register_Greeter(s, opts)
	Register_Spillexplore(s, opts)
}
