// Code generated by mcpgen. DO NOT EDIT.

package tools

import (
	"context"

	src "github.com/fzxbl/mcp-toolify/example/greeter"
	"github.com/fzxbl/mcp-toolify/runtime"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// greeter.greet input
type GreeterGreetInput struct {
	Name    string `json:"name" jsonschema:"要问候的名字"`
	Excited bool   `json:"excited" jsonschema:"是否在结尾加感叹号"`
}

func handle_greeter_Greet(ctx context.Context, req *mcp.CallToolRequest, in GreeterGreetInput) (*mcp.CallToolResult, any, error) {
	out, callErr := src.Greet(in.Name, in.Excited)
	if callErr != nil {
		return runtime.ToolError(callErr), nil, nil
	}
	return runtime.MaybeSpill("greeter.greet", out, map[string]any{"result": out})
}

func register_handle_greeter_Greet(s *mcp.Server) {
	mcp.AddTool(s, &mcp.Tool{
		Name:        "greeter.greet",
		Description: "生成一句问候语。",
	}, handle_greeter_Greet)
}

// greeter.add_numbers input
type GreeterAddNumbersInput struct {
	A int `json:"a" jsonschema:"第一个加数"`
	B int `json:"b" jsonschema:"第二个加数"`
}

func handle_greeter_AddNumbers(ctx context.Context, req *mcp.CallToolRequest, in GreeterAddNumbersInput) (*mcp.CallToolResult, any, error) {
	out := src.AddNumbers(in.A, in.B)
	return runtime.MaybeSpill("greeter.add_numbers", out, map[string]any{"result": out})
}

func register_handle_greeter_AddNumbers(s *mcp.Server) {
	mcp.AddTool(s, &mcp.Tool{
		Name:        "greeter.add_numbers",
		Description: "返回两个整数之和（演示多返回值按变量名打包）。",
	}, handle_greeter_AddNumbers)
}

func Register_Greeter(s *mcp.Server, opts runtime.RegisterOptions) {
	if opts.Allow("greeter", []string{"read"}) {
		register_handle_greeter_Greet(s)
		runtime.RegisterMeta(runtime.ToolMeta{Name: "greeter.greet", Capability: runtime.ReadOnly, Risk: runtime.RiskNone})
	}
	if opts.Allow("greeter", []string{}) {
		register_handle_greeter_AddNumbers(s)
		runtime.RegisterMeta(runtime.ToolMeta{Name: "greeter.add_numbers", Capability: runtime.ReadOnly, Risk: runtime.RiskNone})
	}
}
