// Code generated by mcpgen. DO NOT EDIT.

package tools

import (
	"context"

	"github.com/fzxbl/mcp-toolify/runtime"
	src "github.com/fzxbl/mcp-toolify/spillexplore"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// spill_explore input
type SpillexploreSpillExploreInput struct {
	Id         string `json:"id" jsonschema:"spill 资源 id（spill:// 后面那段）"`
	Op         string `json:"op" jsonschema:"操作：stat / read / grep / schema / jq"`
	LineOffset int    `json:"line_offset" jsonschema:"read 起始行（0 基）"`
	Limit      int    `json:"limit" jsonschema:"read/grep 返回行数上限（jsonl 首次探索建议 limit=1）"`
	Pattern    string `json:"pattern" jsonschema:"grep 正则"`
	JqExpr     string `json:"jq_expr" jsonschema:"jq 表达式（仅 json/jsonl）"`
	Depth      int    `json:"depth" jsonschema:"schema 递归展开层数（<=0 时默认 2）"`
	MaxBytes   int    `json:"max_bytes" jsonschema:" 返回字节上限（<=0 时默认 1MB）"`
}

func handle_spillexplore_SpillExplore(ctx context.Context, req *mcp.CallToolRequest, in SpillexploreSpillExploreInput) (*mcp.CallToolResult, any, error) {
	out, callErr := src.SpillExplore(in.Id, in.Op, in.LineOffset, in.Limit, in.Pattern, in.JqExpr, in.Depth, in.MaxBytes)
	if callErr != nil {
		return runtime.ToolError(callErr), nil, nil
	}
	return runtime.MaybeSpill("spill_explore", out, map[string]any{"result": out})
}

func register_handle_spillexplore_SpillExplore(s *mcp.Server) {
	mcp.AddTool(s, &mcp.Tool{
		Name:        "spill_explore",
		Description: "探索任意 spill 资源（read/grep/schema/jq），对 json/jsonl/text 通用。 | 核心原则：写 jq/grep 前先摸清真实结构（字段名、大小写、规模），不要凭 skill 文档里的 fields 名想当然——按下面各格式的\"先看结构\"方式确认后再提取。必要时先 op=stat 看大小/行数。 | 按格式选择操作： - jsonl（一行一条记录，如批量结果）：先 op=read limit=1 读 1 行看清单条记录的真实字段与 大小写，再写 op=jq（逐行执行）提取；也可 op=schema 取首行推断结构（配 depth 深看嵌套）； 翻页用 op=read/op=grep 按行。 - json（单个 JSON 对象/数组）：整份是一个值，read 一行往往就是全部内容、意义不大；应先 op=schema 看整体结构（配 depth 展开嵌套），再用 op=jq 按路径提取。 - text（扫日志等非结构化文本）：只用 op=read 行偏移分页 + op=grep 正则过滤；不支持 schema/jq。 | 返回：探索结果；error 表示资源不存在或参数错误。",
	}, handle_spillexplore_SpillExplore)
}

func Register_Spillexplore(s *mcp.Server, opts runtime.RegisterOptions) {
	if opts.Allow("spillexplore", []string{"read", "spill"}) {
		register_handle_spillexplore_SpillExplore(s)
		runtime.RegisterMeta(runtime.ToolMeta{Name: "spill_explore", Capability: runtime.ReadOnly, Risk: runtime.RiskLow})
	}
}
